### ISSUE TITLE
Add Pacman clock like mario-bros-master

### ISSUE THREAD

**Issue by nodoubtman** [jnthas/clockwise#10]
Hello..

Can you add Pacman, as mario-bros-master

i don't know how to assemble all this...

Thanks.
Marc.

**Comment by Lofty73** [comment]
Pac man is included in the web based installer follow the instructions on the main clockwise page

**Comment by nodoubtman** [comment]
I know :)
But i want to customize it, like to display the date in french, etc :)

Thank you so much!!!: )
Marc.

**Comment by Lofty73** [comment]
Apologies I understand

**Comment by jnthas** [comment]
Hi @nodoubtman, in order to have the Pacman set please clone the repo https://github.com/jnthas/clockwise first. Then change directory to `clockwise/firmware/lib` and clone the Pacman's clockface https://github.com/jnthas/cw-cf-0x05 there. You should be good to go.

**Comment by nodoubtman** [comment]
Thank you so much :)
Working :)

**Comment by nodoubtman** [comment]
> Hi @nodoubtman, in order to have the Pacman set please clone the repo https://github.com/jnthas/clockwise first. Then change directory to `clockwise/firmware/lib` and clone the Pacman's clockface https://github.com/jnthas/cw-cf-0x05 there. You should be good to go.

Excuse me my ignorance, but how do i open it with platform io?

Thanks.
Marc.
