### ISSUE TITLE
Doesn't seem to be working for P3 matrix

### ISSUE THREAD

**Issue by zombodotcom** [jnthas/clockwise#11]
![image](https://user-images.githubusercontent.com/13477955/211232657-6db2dd0f-e444-4b86-b156-1be2665d6865.png)

This turns on the board and displays correctly during setup.

With 
```
HUB75_I2S_CFG::i2s_pins _pins={R1_PIN, G1_PIN, B1_PIN, R2_PIN, G2_PIN, B2_PIN, A_PIN, B_PIN, C_PIN, D_PIN, E_PIN, LAT_PIN, OE_PIN, CLK_PIN};
HUB75_I2S_CFG mxconfig(
                      64,   // width
                      64,   // height
                      2,   // chain length
                   _pins
);
```

this setup also works for SmartMatrix and ESP32-HUB75-MatrixPanel-I2S-DMA

it's connected and saying collision detected but nothing is being drawn. I am using the mario sketch. and included the clockface.h and stuff from that folder. 

![image](https://user-images.githubusercontent.com/13477955/211232748-dffff960-505b-4753-bea5-b8b275f0f397.png)

I have also gotten the wifi to work. Nothing works past the initial test that the panel Pinout is working.

**Comment by zombodotcom** [comment]
this seems to have to do with the [ESP32-HUB75-MatrixPanel-DMA](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA) library. it will display RGB for 

```

  dma_display->fillScreenRGB888(128,0,0);
  delay(1000);
  dma_display->fillScreenRGB888(0,0,128);
  delay(1000);
  dma_display->clearScreen();  
  delay(1000);  
  ```

at start. but the fastLED side isn't working, so far. 

The plasma pattern works, but its not calling anything in fastled other than color.

**Comment by zombodotcom** [comment]
for anyone else having this issue,


you need to edit the 
`ESP32-HUB75-MatrixPanel-I2S-DMA.h` file to be the correct MATRIX_HEIGHT and MATRIX_WIDTH

![image](https://user-images.githubusercontent.com/13477955/215633299-6f117238-8a0c-4339-88d8-e1c8315190da.png)

also 

the default pins

![image](https://user-images.githubusercontent.com/13477955/215633463-0b5035e0-8564-45a6-a3fe-bc2438814c74.png)

**Comment by jnthas** [comment]
I'm happy you found the solution and share it here. Thanks
