### ISSUE TITLE
AM / PM label in 24 H mode

### ISSUE THREAD

**Issue by Burkadius1952** [jnthas/clockwise#19]
Hello Jonathas. Thank you for the new clockface. I have installed it and it works. But I have a question about the display of the time in 24-hour format: Why is there still the "A" or the "P"? You don't need that. And then it would be better and visually nicer if the 24-hour format didn't say 8:24 but 08:24. Otherwise everything is great as always and maybe with a new release my wish for the display OFF night switch or an ABC control will come true.
best regards
Burkhard

**Comment by jnthas** [comment]
Fixed in the latest version 
https://github.com/jnthas/clockwise/releases/tag/v1.2.1

Closing issue
