### ISSUE TITLE
Connecting LDR

### ISSUE THREAD

**Issue by anthonyjclarke** [jnthas/clockwise#25]
Thanks for the great addition, can you please confirm how to connect the LDR to Pin35 for your code to operate?

Is it as per this ESP Trinity schematic? 
<img width="217" alt="image" src="https://github.com/jnthas/clockwise/assets/9491428/71c6cb9d-74fa-40df-874a-c434d5dee5a3">

https://github.com/witnessmenow/ESP32-Trinity/blob/master/hardware/ESP32Trinity/V1.2/Schematic_ESP32-Trinity_2021-08-27.png

**Comment by jnthas** [comment]
Hi Anthony. Sorry, it's exactly this. I'm going to update the documentation.

**Comment by TheGroundZero** [comment]
If you get the Trinity, is it a matter of just soldering the LDR on the provisioned pads?

**Comment by Lofty73** [comment]
Yes just solder one to the marked position.

**Comment by hallard** [comment]
Awesome software, would be great to be able to select GPIO used for LDR in settings page to avoid users to recompile.
I'm Author of an old OpenSource [shield](https://github.com/hallard/WeMos-Matrix-Shield-DMA) for ESP32 D1 Mini and as I wanted to keep compatibility with ESP8266 D1 Mini, LDR is connected to A0 AKA `GPIO36` on ESP32 D1 Mini

**Comment by jnthas** [comment]
@anthonyjclarke I added the LDR wiring in the [README](https://github.com/jnthas/clockwise#connecting-the-ldr) 
@hallard Thanks for the feedback, I will put this change in the backlog. If you don't mind, I will link your shield as one of the options to run the Clockwise.

**Comment by anthonyjclarke** [comment]
> Awesome software, would be great to be able to select GPIO used for LDR in settings page to avoid users to recompile.
> 
> I'm Author of an old OpenSource [shield](https://github.com/hallard/WeMos-Matrix-Shield-DMA) for ESP32 D1 Mini and as I wanted to keep compatibility with ESP8266 D1 Mini, LDR is connected to A0 AKA `GPIO36` on ESP32 D1 Mini
> 
> 

+1 to this. I have some of Charles great boards as well as the I2S board from @witnessmenow boards and would like this flexibility

**Comment by jnthas** [comment]
I agree. I will include the option to configure the GPIO in the next release.

**Comment by hallard** [comment]
> I agree. I will include the option to configure the GPIO in the next release.

Awesome, thanks 🙏

**Comment by hallard** [comment]
> 



> If you don't mind, I will link your shield as one of the options to run the Clockwise.

Of course you’re welcome
