### ISSUE TITLE
Feature Request: Show firmware version on Settings page

### ISSUE THREAD

**Issue by TheGroundZero** [jnthas/clockwise#28]
To make it easier to identify which firmware version you have, it would be nice to see it displayed on the settings page.

Would also be nice if this version could be exposed via an API so I could read it in e.g. Home Assistant, where I can match it against the latest release of this Github repo so I know an update is available.

**Comment by jnthas** [comment]
Great suggestion. Will add it in the backlog

**Comment by jnthas** [comment]
Done in this release https://twitter.com/jnthas/status/1667988156220620801?s=20

**Comment by TheGroundZero** [comment]
Saw the Twitter post 🎉
