### ISSUE TITLE
WifiConnect Password not documented

### ISSUE THREAD

**Issue by thilomichael** [jnthas/clockwise#3]
Hi,

Thank you for this awesome project! I tried to flash the examples over the web interface, and everything went fine. However, the ClockwiseWifi has a password set that is not documented everywhere and is not printed in the console. I found it somewhere in the code and would suggest adding the SSID and password to the clockwise.page.

Best,
Thilo

**Comment by jnthas** [comment]
Hello, Thilo. Thanks for pointing out, I really missed it. Already did the change.
