### ISSUE TITLE
Clock Request: Daylight Map

### ISSUE THREAD

**Issue by hooperalex** [jnthas/clockwise#30]
How hard would it be to create something like the following?
https://s3-media1.fl.yelpcdn.com/bphoto/8hrn3DWyTbdI9DxT-MStNg/o.jpg

**Comment by jnthas** [comment]
Hey. This was my first intention when I did the World Map Clock, actually I got there but I didn't like the final result.  
https://github.com/jnthas/cw-cf-0x03/blob/main/worldclock.gif
I wrote the functions to do that in an old Display file that was in https://github.com/jnthas/clockwise/tree/main/firmware/lib/cw-gfx-engine. Have to seek in the git history.
