### ISSUE TITLE
Turn the display on/off (or adjust brightness) remotely

### ISSUE THREAD

**Issue by joelhauxwell** [jnthas/clockwise#32]
I built this last week for my 6yo son and he LOVES it - thankyou for an amazing project.

It would be awesome if it could be controlled remotely - maybe via MQTT?  He isn't in his room most of the day (while as school!) and i could set up an automation in home assistant/node red to turn it off/on.

Unfortunately I do not have the programming skills to add this feature and have no idea how big the task would be to know if its even reasonable to ask!

Some pics of the build for anyone interested (i used a photo frame from IKEA and 3D printed a bezel):

![20230531_131747](https://github.com/jnthas/clockwise/assets/71120697/f6a25008-e43e-43e5-b111-5a49f4e27613)

![20230531_132021](https://github.com/jnthas/clockwise/assets/71120697/7ad407ad-3dc1-4721-96dd-9f094a3e333d)

![20230531_131959](https://github.com/jnthas/clockwise/assets/71120697/5abaf45c-4d35-435c-9643-843160342126)

![20230531_132038](https://github.com/jnthas/clockwise/assets/71120697/f4294f5c-9ec3-40f2-a2c9-6e085323c67e)

**Comment by jnthas** [comment]
That's amazing! I don't know if you like, but a matte acrylic in front of display with the frame will be even better. Congrats anyways. Please, if you share the design of 3d printed parts I will find some place to make it available for everyone.

Answering your question, it's possible make an HTTP request and set the display bright to zero. I replied a similar question here https://github.com/jnthas/clockwise/issues/18

**Comment by joelhauxwell** [comment]
Thankyou for the link to the previous question/answer about remote control - i have been able to integrate it with Home Assistant and its working great!

Of course id be happy to share more details of what I put together - just let me know when there is a place.

Joel.

**Comment by mateuszdrab** [comment]
Wow, I like that frame @joelhauxwell. 
I've just put my display on a tablet stand as I wasn't sure what to use as a frame.

I guess the best place to share would be your own github repo with a readme page and perhaps the 3d design files, maybe the link to the Ikea product. 

If you do this, I'll definitely make one for myself.

**Comment by jnthas** [comment]
I agree. Please, share it in a Github repo or on websites like Thingiverse.
