### ISSUE TITLE
API endpoints list

### ISSUE THREAD

**Issue by mateuszdrab** [jnthas/clockwise#40]
Hey @jnthas 

I was wondering if you have a list of endpoints available via HTTP?

The issue I have is that my ESP32 board seems to have very bad Wi-Fi signal, the web UI barely ever loads but when using the `/set?displayBright=`, I noticed I can make it work much more reliably.

Thanks

**Comment by jnthas** [comment]
Hello Mateus. I didn't have time to create a documentation for that yet (it's a good idea), but you can take a look at the code. The handling of path and methods is very rudimentary but you can get the idea there https://github.com/jnthas/clockwise/blob/9e3924bcb3825f85069d636e52a583853bb443f7/firmware/lib/cw-commons/CWWebServer.h#L80C6-L80C6

And the path `/set` can be used with the following parameters
https://github.com/jnthas/clockwise/blob/9e3924bcb3825f85069d636e52a583853bb443f7/firmware/lib/cw-commons/CWPreferences.h#L9

**Comment by mateuszdrab** [comment]
Thanks Jonathas

I was just having a look to see what I can do. I also wanted to make sure that WiFi password can't be read from the device, in case it goes into AP mode.

Is it possible to disable AP mode somehow?

**Comment by jnthas** [comment]
There is not an easy way to do it, you would have to recompile after removing this line 
https://github.com/jnthas/clockwise/blob/cb6291876f8637978725eea3f3f071c1c9888162/firmware/lib/cw-commons/WiFiController.h#L98C24-L98C24

I didn't understand your question about the Wifi Password, as far as I know, the wifi password can't be read in the WiFi Manager as I don't set it during the AP setup.
