### ISSUE TITLE
how to set raw.githubusercontent.com to point to forked directory? (just a question)

### ISSUE THREAD

**Issue by robegamesios** [jnthas/clockwise#54]
hi @jnthas can you show me how to reconfigure raw.githubusercontent.com to point to my forked shared folder? thank you

**Comment by robegamesios** [comment]
if i enter an invalid (or unreachable) hostname, the panel gets stuck with the Splash screen "Downloading" screen. 

not sure why the panel cannot download the raw json (e.g. https://raw.githubusercontent.com/robegamesios/clock-club/main/shared/donkey-kong.json) and just gets stuck with the splash screen

i updated this:
```if (server.startsWith("raw.")) {
    port = 443;
    file = String("/robegamesios/clock-club/main/shared" + file);
  }```
is there another place i should update? thanks

**Comment by robegamesios** [comment]
@jnthas i figured out the issue of the SSL- memory allocation failed when trying to build on PlatformIO.  you will need to downgrade the espressif32 framework

`platform = espressif32 @ ^5.4.0`

that fixed the issue. I am also able to access the clockfaces for canvas on my forked repo.

https://github.com/robegamesios/clockwise/blob/main/firmware/platformio.ini

just incase someone else encounters this issue. 

closing this

**Comment by jnthas** [comment]
Great. Thank you.
